const en = {
  fleetCheck: 'FleetCheck', driverName: 'Driver Name', tlNumber: 'TL / Employee Number', startVehicleCheck: 'START VEHICLE CHECK', vehicle: 'Vehicle', vehicleOk: 'Is the vehicle OK?', everythingOk: 'EVERYTHING OK', reportIssue: 'REPORT ISSUE', knownIssues: 'Known Issues', noActiveIssues: 'No active issues.', tire: 'Tire', fuel: 'Fuel', adBlue: 'AdBlue', oilService: 'Oil / Service', lights: 'Lights', damage: 'Damage', warningLight: 'Warning Light', other: 'Other', description: 'Short description', addPhoto: 'Add Photo', sendReport: 'SEND REPORT', back: 'Back', success: 'Success', vehicleCheckSaved: 'Vehicle check saved', issueReported: 'Issue reported', adminLogin: 'Admin Login', email: 'Email', password: 'Password', login: 'LOGIN', dashboard: 'Dashboard', totalVehicles: 'Total Vehicles', vehiclesOk: 'Vehicles OK', needAttention: 'Need Attention', urgent: 'Urgent', recentReports: 'Recent Reports', driver: 'Driver', issue: 'Issue', status: 'Status', date: 'Date', open: 'OPEN', inRepair: 'IN REPAIR', resolved: 'RESOLVED', checkInHint: 'Enter your details before starting your shift.', viewKnownIssues: 'View known issues', noReports: 'No reports yet.', loginError: 'Email or password is incorrect.', reportHint: 'Review known issues before you drive.', reported: 'Reported', required: 'Choose a category and describe the issue.', activeIssue: 'Active issue', photo: 'Photo', demoCredentials: 'Demo: admin@fleetcheck.local / fleetcheck'
}

const de = { ...en, driverName: 'Fahrername', tlNumber: 'TL / Mitarbeiternummer', startVehicleCheck: 'FAHRZEUGCHECK STARTEN', vehicle: 'Fahrzeug', vehicleOk: 'Ist das Fahrzeug in Ordnung?', everythingOk: 'ALLES IN ORDNUNG', reportIssue: 'PROBLEM MELDEN', knownIssues: 'Bekannte Probleme', noActiveIssues: 'Keine aktiven Probleme.', tire: 'Reifen', fuel: 'Kraftstoff', lights: 'Beleuchtung', damage: 'Schaden', warningLight: 'Warnleuchte', other: 'Sonstiges', description: 'Kurze Beschreibung', addPhoto: 'Foto hinzufügen', sendReport: 'MELDUNG SENDEN', back: 'Zurück', success: 'Erfolg', vehicleCheckSaved: 'Fahrzeugcheck gespeichert', issueReported: 'Problem gemeldet', adminLogin: 'Admin-Anmeldung', password: 'Passwort', login: 'ANMELDEN', totalVehicles: 'Fahrzeuge gesamt', vehiclesOk: 'Fahrzeuge OK', needAttention: 'Aufmerksamkeit nötig', urgent: 'Dringend', recentReports: 'Aktuelle Meldungen', driver: 'Fahrer', issue: 'Problem', date: 'Datum', open: 'OFFEN', inRepair: 'IN REPARATUR', resolved: 'GELÖST', checkInHint: 'Bitte geben Sie Ihre Daten ein, bevor Sie losfahren.', viewKnownIssues: 'Bekannte Probleme ansehen', noReports: 'Noch keine Meldungen vorhanden.', loginError: 'E-Mail oder Passwort ist nicht korrekt.', reportHint: 'Bitte prüfen Sie bekannte Probleme vor der Fahrt.', reported: 'Gemeldet', required: 'Bitte wählen Sie eine Kategorie und beschreiben Sie das Problem.', activeIssue: 'Aktives Problem', photo: 'Foto', demoCredentials: 'Demo: admin@fleetcheck.local / fleetcheck' }
const ru = { ...en, driverName: 'Имя водителя', tlNumber: 'TL / Номер сотрудника', startVehicleCheck: 'НАЧАТЬ ПРОВЕРКУ', vehicle: 'Автомобиль', vehicleOk: 'Автомобиль в порядке?', everythingOk: 'ВСЕ В ПОРЯДКЕ', reportIssue: 'СООБЩИТЬ О ПРОБЛЕМЕ', knownIssues: 'Известные проблемы', noActiveIssues: 'Нет активных проблем.', tire: 'Шина', fuel: 'Топливо', oilService: 'Масло / Сервис', lights: 'Освещение', damage: 'Повреждение', warningLight: 'Сигнальная лампа', other: 'Другое', description: 'Краткое описание', addPhoto: 'Добавить фото', sendReport: 'ОТПРАВИТЬ ОТЧЕТ', back: 'Назад', success: 'Успешно', vehicleCheckSaved: 'Проверка автомобиля сохранена', issueReported: 'Проблема зарегистрирована', adminLogin: 'Вход администратора', password: 'Пароль', login: 'ВОЙТИ', dashboard: 'Панель управления', totalVehicles: 'Всего автомобилей', vehiclesOk: 'Автомобили в порядке', needAttention: 'Требуют внимания', urgent: 'Срочно', recentReports: 'Последние отчеты', driver: 'Водитель', issue: 'Проблема', date: 'Дата', open: 'ОТКРЫТО', inRepair: 'В РЕМОНТЕ', resolved: 'РЕШЕНО' }
const lv = { ...en, driverName: 'Vadītāja vārds', tlNumber: 'TL / Darbinieka numurs', startVehicleCheck: 'SĀKT AUTO PĀRBAUDI', vehicle: 'Transportlīdzeklis', vehicleOk: 'Vai transportlīdzeklis ir kārtībā?', everythingOk: 'VISS KĀRTĪBĀ', reportIssue: 'ZIŅOT PAR PROBLĒMU', knownIssues: 'Zināmās problēmas', noActiveIssues: 'Nav aktīvu problēmu.', tire: 'Riepa', fuel: 'Degviela', oilService: 'Eļļa / Serviss', lights: 'Apgaismojums', damage: 'Bojājums', warningLight: 'Brīdinājuma gaisma', other: 'Cits', description: 'Īss apraksts', addPhoto: 'Pievienot foto', sendReport: 'SŪTĪT ZIŅOJUMU', back: 'Atpakaļ', success: 'Veiksmīgi', vehicleCheckSaved: 'Transportlīdzekļa pārbaude saglabāta', issueReported: 'Problēma reģistrēta', adminLogin: 'Administratora pieslēgšanās', password: 'Parole', login: 'PIESLĒGTIES', dashboard: 'Vadības panelis', totalVehicles: 'Kopā transportlīdzekļu', vehiclesOk: 'Transportlīdzekļi kārtībā', needAttention: 'Nepieciešama uzmanība', urgent: 'Steidzami', recentReports: 'Pēdējie ziņojumi', driver: 'Vadītājs', issue: 'Problēma', date: 'Datums', open: 'ATVĒRTS', inRepair: 'REMONTĀ', resolved: 'ATRISINĀTS' }

Object.assign(en, { knownIssue: 'KNOWN ISSUE', knownIssueHint: 'Please review this issue before continuing.', seenIssue: 'I HAVE SEEN THIS', beforeDriving: 'Before driving', reportProblem: 'REPORT A PROBLEM', reportSent: 'REPORT SENT', thankYou: 'Thank you.', issueReportedDetail: 'The issue has been reported.' })
Object.assign(de, { knownIssue: 'BEKANNTES PROBLEM', knownIssueHint: 'Bitte prüfen Sie dieses Problem, bevor Sie fortfahren.', seenIssue: 'ICH HABE ES GESEHEN', beforeDriving: 'Vor der Fahrt', reportProblem: 'PROBLEM MELDEN', reportSent: 'MELDUNG GESENDET', thankYou: 'Vielen Dank.', issueReportedDetail: 'Das Problem wurde gemeldet.' })
Object.assign(ru, { knownIssue: 'ИЗВЕСТНАЯ ПРОБЛЕМА', knownIssueHint: 'Пожалуйста, ознакомьтесь с проблемой перед продолжением.', seenIssue: 'Я ОЗНАКОМИЛСЯ', beforeDriving: 'Перед поездкой', reportProblem: 'СООБЩИТЬ О ПРОБЛЕМЕ', reportSent: 'ОТЧЕТ ОТПРАВЛЕН', thankYou: 'Спасибо.', issueReportedDetail: 'Проблема зарегистрирована.' })
Object.assign(lv, { knownIssue: 'ZINĀMA PROBLĒMA', knownIssueHint: 'Pirms turpināt, lūdzu, apskatiet šo problēmu.', seenIssue: 'ES TO ESMU REDZĒJIS', beforeDriving: 'Pirms braukšanas', reportProblem: 'ZIŅOT PAR PROBLĒMU', reportSent: 'ZIŅOJUMS NOSŪTĪTS', thankYou: 'Paldies.', issueReportedDetail: 'Par problēmu ir ziņots.' })

Object.assign(en, { logout: 'Logout', endShift: 'END SHIFT' })
Object.assign(de, { logout: 'Abmelden', endShift: 'SCHICHT BEENDEN' })
Object.assign(ru, { logout: 'Выйти', endShift: 'ЗАВЕРШИТЬ СМЕНУ' })
Object.assign(lv, { logout: 'Iziet', endShift: 'BEIGT MAIŅU' })

Object.assign(en, { vehicleNotFound: 'Vehicle not found', vehicleNotFoundHint: 'This QR code does not match a registered vehicle.' })
Object.assign(de, { vehicleNotFound: 'Fahrzeug nicht gefunden', vehicleNotFoundHint: 'Dieser QR-Code gehört zu keinem registrierten Fahrzeug.' })
Object.assign(ru, { vehicleNotFound: 'Автомобиль не найден', vehicleNotFoundHint: 'Этот QR-код не соответствует зарегистрированному автомобилю.' })
Object.assign(lv, { vehicleNotFound: 'Transportlīdzeklis nav atrasts', vehicleNotFoundHint: 'Šis QR kods neatbilst reģistrētam transportlīdzeklim.' })

Object.assign(en, { fleetVehicles: 'Fleet Vehicles', lastActivity: 'Last activity', vehicleHistory: 'Vehicle History', backToDashboard: 'Back to Dashboard' })
Object.assign(de, { fleetVehicles: 'Fuhrparkfahrzeuge', lastActivity: 'Letzte Aktivität', vehicleHistory: 'Fahrzeughistorie', backToDashboard: 'Zurück zum Dashboard' })
Object.assign(ru, { fleetVehicles: 'Автомобили автопарка', lastActivity: 'Последняя активность', vehicleHistory: 'История автомобиля', backToDashboard: 'Назад к панели управления' })
Object.assign(lv, { fleetVehicles: 'Autoparka transportlīdzekļi', lastActivity: 'Pēdējā darbība', vehicleHistory: 'Transportlīdzekļa vēsture', backToDashboard: 'Atpakaļ uz paneli' })

Object.assign(en, { manualCheckIn: 'Manual vehicle check-in', manualCheckInHint: 'Enter the vehicle license plate to start your check.', licensePlate: 'Vehicle License Plate', manualVehicleNotFound: 'Vehicle not found. Please check the license plate.' })
Object.assign(de, { manualCheckIn: 'Manuelle Fahrzeuganmeldung', manualCheckInHint: 'Geben Sie das Fahrzeugkennzeichen ein, um den Check zu starten.', licensePlate: 'Fahrzeugkennzeichen', manualVehicleNotFound: 'Fahrzeug nicht gefunden. Bitte prüfen Sie das Kennzeichen.' })
Object.assign(ru, { manualCheckIn: 'Ручная регистрация автомобиля', manualCheckInHint: 'Введите номер автомобиля, чтобы начать проверку.', licensePlate: 'Номер автомобиля', manualVehicleNotFound: 'Автомобиль не найден. Проверьте номер автомобиля.' })
Object.assign(lv, { manualCheckIn: 'Manuāla transportlīdzekļa reģistrācija', manualCheckInHint: 'Ievadiet transportlīdzekļa numuru, lai sāktu pārbaudi.', licensePlate: 'Transportlīdzekļa numurs', manualVehicleNotFound: 'Transportlīdzeklis nav atrasts. Pārbaudiet numuru.' })

Object.assign(en, { plate: 'Plate', addVehicleQuestion: 'Add this vehicle to FleetCheck?', addVehicle: 'ADD VEHICLE', cancel: 'CANCEL', addedManually: 'NEW', addedBy: 'Added by' })
Object.assign(de, { plate: 'Kennzeichen', addVehicleQuestion: 'Dieses Fahrzeug zu FleetCheck hinzufügen?', addVehicle: 'FAHRZEUG HINZUFÜGEN', cancel: 'ABBRECHEN', addedManually: 'NEU', addedBy: 'Hinzugefügt von' })
Object.assign(ru, { plate: 'Номер', addVehicleQuestion: 'Добавить этот автомобиль в FleetCheck?', addVehicle: 'ДОБАВИТЬ АВТОМОБИЛЬ', cancel: 'ОТМЕНА', addedManually: 'НОВЫЙ', addedBy: 'Добавил' })
Object.assign(lv, { plate: 'Numurs', addVehicleQuestion: 'Pievienot šo transportlīdzekli FleetCheck?', addVehicle: 'PIEVIENOT TRANSPORTLĪDZEKLI', cancel: 'ATCELT', addedManually: 'JAUNS', addedBy: 'Pievienoja' })

Object.assign(en, { addedOn: 'Added on' })
Object.assign(de, { addedOn: 'Hinzugefügt am' })
Object.assign(ru, { addedOn: 'Добавлен' })
Object.assign(lv, { addedOn: 'Pievienots' })

Object.assign(en, { depot: 'Depot', all: 'ALL' })
Object.assign(de, { depot: 'Depot', all: 'ALLE' })
Object.assign(ru, { depot: 'Депо', all: 'ВСЕ' })
Object.assign(lv, { depot: 'Depo', all: 'VISI' })

Object.assign(en, { welcomeTitle: 'Digital Vehicle Inspection & Handover', welcomeCopy: 'Check vehicles, document their condition and report problems in seconds.', driverEmployee: 'DRIVER / EMPLOYEE', startInspection: 'Start vehicle inspection', admin: 'ADMIN', fleetDashboard: 'Fleet management dashboard' })
Object.assign(de, { welcomeTitle: 'Digitale Fahrzeugprüfung & Übergabe', welcomeCopy: 'Prüfen Sie Fahrzeuge, dokumentieren Sie ihren Zustand und melden Sie Probleme in Sekunden.', driverEmployee: 'FAHRER / MITARBEITER', startInspection: 'Fahrzeugprüfung starten', admin: 'ADMIN', fleetDashboard: 'Fuhrpark-Dashboard' })
Object.assign(ru, { welcomeTitle: 'Цифровая проверка и передача автомобиля', welcomeCopy: 'Проверяйте автомобили, документируйте состояние и сообщайте о проблемах за секунды.', driverEmployee: 'ВОДИТЕЛЬ / СОТРУДНИК', startInspection: 'Начать проверку автомобиля', admin: 'АДМИН', fleetDashboard: 'Панель управления автопарком' })
Object.assign(lv, { welcomeTitle: 'Digitāla transportlīdzekļa pārbaude un nodošana', welcomeCopy: 'Pārbaudiet transportlīdzekļus, dokumentējiet to stāvokli un ziņojiet par problēmām dažu sekunžu laikā.', driverEmployee: 'VADĪTĀJS / DARBINIEKS', startInspection: 'Sākt transportlīdzekļa pārbaudi', admin: 'ADMINISTRATORS', fleetDashboard: 'Autoparka vadības panelis' })

Object.assign(en, { simpleCheckInHint: 'Enter the vehicle number and your name.', vehicleNumber: 'Vehicle Number', yourName: 'Your Name', startCheck: 'START CHECK' })
Object.assign(de, { simpleCheckInHint: 'Geben Sie die Fahrzeugnummer und Ihren Namen ein.', vehicleNumber: 'Fahrzeugnummer', yourName: 'Ihr Name', startCheck: 'CHECK STARTEN' })
Object.assign(ru, { simpleCheckInHint: 'Введите номер автомобиля и ваше имя.', vehicleNumber: 'Номер автомобиля', yourName: 'Ваше имя', startCheck: 'НАЧАТЬ ПРОВЕРКУ' })
Object.assign(lv, { simpleCheckInHint: 'Ievadiet transportlīdzekļa numuru un savu vārdu.', vehicleNumber: 'Transportlīdzekļa numurs', yourName: 'Jūsu vārds', startCheck: 'SĀKT PĀRBAUDI' })

Object.assign(en, { publicWelcomeTitle: 'Your vehicle. Its condition. Its history.', publicWelcomeCopy: 'Document vehicle condition, problems and handovers with photos and videos.', myVehicle: 'MY VEHICLE', privateOwners: 'For private vehicle owners', privateDescription: 'Track problems, photos, videos and vehicle history.', companyFleet: 'COMPANY FLEET', businessFleets: 'For businesses and vehicle fleets', companyDescription: 'Check vehicles before and after use and document damage or problems.', continue: 'CONTINUE', companyAdminLogin: 'Company Admin Login' })
Object.assign(de, { publicWelcomeTitle: 'Ihr Fahrzeug. Sein Zustand. Seine Geschichte.', publicWelcomeCopy: 'Dokumentieren Sie Fahrzeugzustand, Probleme und Uebergaben mit Fotos und Videos.', myVehicle: 'MEIN FAHRZEUG', privateOwners: 'Fuer private Fahrzeughalter', privateDescription: 'Behalten Sie Probleme, Fotos, Videos und die Fahrzeughistorie im Blick.', companyFleet: 'UNTERNEHMENSFUHRPARK', businessFleets: 'Fuer Unternehmen und Fahrzeugflotten', companyDescription: 'Pruefen Sie Fahrzeuge vor und nach der Nutzung und dokumentieren Sie Schaeden oder Probleme.', continue: 'WEITER', companyAdminLogin: 'Unternehmens-Admin-Anmeldung' })
Object.assign(ru, { publicWelcomeTitle: 'Ваш автомобиль. Его состояние. Его история.', publicWelcomeCopy: 'Документируйте состояние автомобиля, проблемы и передачи с фото и видео.', myVehicle: 'МОЙ АВТОМОБИЛЬ', privateOwners: 'Для частных владельцев автомобилей', privateDescription: 'Отслеживайте проблемы, фото, видео и историю автомобиля.', companyFleet: 'АВТОПАРК КОМПАНИИ', businessFleets: 'Для компаний и автопарков', companyDescription: 'Проверяйте автомобили до и после использования и документируйте повреждения или проблемы.', continue: 'ПРОДОЛЖИТЬ', companyAdminLogin: 'Вход администратора компании' })
Object.assign(lv, { publicWelcomeTitle: 'Jūsu transportlīdzeklis. Tā stāvoklis. Tā vēsture.', publicWelcomeCopy: 'Dokumentējiet transportlīdzekļa stāvokli, problēmas un nodošanu ar foto un video.', myVehicle: 'MANS TRANSPORTLĪDZEKLIS', privateOwners: 'Privātiem transportlīdzekļu īpašniekiem', privateDescription: 'Sekojiet problēmām, foto, video un transportlīdzekļa vēsturei.', companyFleet: 'UZŅĒMUMA AUTOPARKS', businessFleets: 'Uzņēmumiem un transportlīdzekļu autoparkiem', companyDescription: 'Pārbaudiet transportlīdzekļus pirms un pēc lietošanas un dokumentējiet bojājumus vai problēmas.', continue: 'TURPINĀT', companyAdminLogin: 'Uzņēmuma administratora pieslēgšanās' })

Object.assign(en, { privateRole: 'PRIVATE', myVehicles: 'My Vehicles', privateHomeHint: 'Add a vehicle to start tracking its condition and history.', addVehicle: 'ADD VEHICLE', brand: 'Brand', model: 'Model', licensePlate: 'License Plate', year: 'Year', saveVehicle: 'SAVE VEHICLE', vehicleOk: 'VEHICLE OK', reportProblem: 'REPORT PROBLEM', vehicleHistory: 'VEHICLE HISTORY', photosVideos: 'PHOTOS / VIDEOS', selectBrand: 'Select a brand', vehicleAlreadyExists: 'This license plate already exists.', vehicleOkSaved: 'Vehicle marked as OK.' })
Object.assign(de, { privateRole: 'PRIVAT', myVehicles: 'Meine Fahrzeuge', privateHomeHint: 'Fügen Sie ein Fahrzeug hinzu, um Zustand und Historie zu verfolgen.', addVehicle: 'FAHRZEUG HINZUFÜGEN', brand: 'Marke', model: 'Modell', licensePlate: 'Kennzeichen', year: 'Jahr', saveVehicle: 'FAHRZEUG SPEICHERN', vehicleOk: 'FAHRZEUG IN ORDNUNG', reportProblem: 'PROBLEM MELDEN', vehicleHistory: 'FAHRZEUGHISTORIE', photosVideos: 'FOTOS / VIDEOS', selectBrand: 'Marke auswählen', vehicleAlreadyExists: 'Dieses Kennzeichen ist bereits vorhanden.', vehicleOkSaved: 'Fahrzeug als in Ordnung markiert.' })
Object.assign(ru, { privateRole: 'ЛИЧНЫЙ', myVehicles: 'Мои автомобили', privateHomeHint: 'Добавьте автомобиль, чтобы отслеживать его состояние и историю.', addVehicle: 'ДОБАВИТЬ АВТОМОБИЛЬ', brand: 'Марка', model: 'Модель', licensePlate: 'Госномер', year: 'Год', saveVehicle: 'СОХРАНИТЬ АВТОМОБИЛЬ', vehicleOk: 'АВТОМОБИЛЬ В ПОРЯДКЕ', reportProblem: 'СООБЩИТЬ О ПРОБЛЕМЕ', vehicleHistory: 'ИСТОРИЯ АВТОМОБИЛЯ', photosVideos: 'ФОТО / ВИДЕО', selectBrand: 'Выберите марку', vehicleAlreadyExists: 'Этот госномер уже существует.', vehicleOkSaved: 'Автомобиль отмечен как исправный.' })
Object.assign(lv, { privateRole: 'PRIVĀTS', myVehicles: 'Mani transportlīdzekļi', privateHomeHint: 'Pievienojiet transportlīdzekli, lai sekotu tā stāvoklim un vēsturei.', addVehicle: 'PIEVIENOT TRANSPORTLĪDZEKLI', brand: 'Marka', model: 'Modelis', licensePlate: 'Reģistrācijas numurs', year: 'Gads', saveVehicle: 'SAGLABĀT TRANSPORTLĪDZEKLI', vehicleOk: 'TRANSPORTLĪDZEKLIS KĀRTĪBĀ', reportProblem: 'ZIŅOT PAR PROBLĒMU', vehicleHistory: 'TRANSPORTLĪDZEKĻA VĒSTURE', photosVideos: 'FOTO / VIDEO', selectBrand: 'Izvēlieties marku', vehicleAlreadyExists: 'Šis reģistrācijas numurs jau pastāv.', vehicleOkSaved: 'Transportlīdzeklis atzīmēts kā kārtībā.' })

Object.assign(en, { shortDescription: 'Short Description', addVideo: 'ADD VIDEO', remove: 'REMOVE' })
Object.assign(de, { shortDescription: 'Kurze Beschreibung', addVideo: 'VIDEO HINZUFÜGEN', remove: 'ENTFERNEN' })
Object.assign(ru, { shortDescription: 'Краткое описание', addVideo: 'ДОБАВИТЬ ВИДЕО', remove: 'УДАЛИТЬ' })
Object.assign(lv, { shortDescription: 'Īss apraksts', addVideo: 'PIEVIENOT VIDEO', remove: 'NOŅEMT' })

Object.assign(en, { welcomeToFleetCheck: 'Welcome to FleetCheck', firstVehiclePrompt: "Let's add your first vehicle.", vehicleType: 'Vehicle Type', car: 'Car', van: 'Van', truck: 'Truck', optional: 'Optional', vehicleAdded: 'Vehicle added', firstVehicleReady: 'Your first vehicle is ready in FleetCheck.', addAnotherVehicle: 'ADD ANOTHER VEHICLE', vehicles: 'VEHICLES', reports: 'REPORTS', companySessionRequired: 'Your company profile is not available. Please return to registration.', companyVehicleExists: 'This license plate is already in your company fleet.' })
Object.assign(de, { welcomeToFleetCheck: 'Willkommen bei FleetCheck', firstVehiclePrompt: 'Lassen Sie uns Ihr erstes Fahrzeug hinzufügen.', vehicleType: 'Fahrzeugtyp', car: 'Auto', van: 'Transporter', truck: 'Lkw', optional: 'Optional', vehicleAdded: 'Fahrzeug hinzugefügt', firstVehicleReady: 'Ihr erstes Fahrzeug ist in FleetCheck bereit.', addAnotherVehicle: 'WEITERES FAHRZEUG HINZUFÜGEN', vehicles: 'FAHRZEUGE', reports: 'MELDUNGEN', companySessionRequired: 'Ihr Unternehmensprofil ist nicht verfügbar. Bitte kehren Sie zur Registrierung zurück.', companyVehicleExists: 'Dieses Kennzeichen ist bereits in Ihrem Unternehmensfuhrpark vorhanden.' })
Object.assign(ru, { welcomeToFleetCheck: 'Добро пожаловать в FleetCheck', firstVehiclePrompt: 'Давайте добавим ваш первый автомобиль.', vehicleType: 'Тип автомобиля', car: 'Легковой автомобиль', van: 'Фургон', truck: 'Грузовик', optional: 'Необязательно', vehicleAdded: 'Автомобиль добавлен', firstVehicleReady: 'Ваш первый автомобиль готов в FleetCheck.', addAnotherVehicle: 'ДОБАВИТЬ ЕЩЕ АВТОМОБИЛЬ', vehicles: 'АВТОМОБИЛИ', reports: 'ОТЧЕТЫ', companySessionRequired: 'Профиль компании недоступен. Вернитесь к регистрации.', companyVehicleExists: 'Этот госномер уже есть в автопарке вашей компании.' })
Object.assign(lv, { welcomeToFleetCheck: 'Laipni lūdzam FleetCheck', firstVehiclePrompt: 'Pievienosim jūsu pirmo transportlīdzekli.', vehicleType: 'Transportlīdzekļa veids', car: 'Auto', van: 'Furgons', truck: 'Kravas auto', optional: 'Neobligāti', vehicleAdded: 'Transportlīdzeklis pievienots', firstVehicleReady: 'Jūsu pirmais transportlīdzeklis ir gatavs FleetCheck.', addAnotherVehicle: 'PIEVIENOT VĒL VIENU TRANSPORTLĪDZEKLI', vehicles: 'TRANSPORTLĪDZEKĻI', reports: 'ZIŅOJUMI', companySessionRequired: 'Jūsu uzņēmuma profils nav pieejams. Lūdzu, atgriezieties reģistrācijā.', companyVehicleExists: 'Šis reģistrācijas numurs jau ir jūsu uzņēmuma autoparkā.' })

Object.assign(en, { companyEntryHint: 'Choose how you want to continue.', vehicleCheck: 'VEHICLE CHECK', driversEmployees: 'For drivers / employees', companyLogin: 'COMPANY LOGIN', existingCompanyAccounts: 'For existing company accounts', createCompanyAccount: 'CREATE COMPANY ACCOUNT', newCompanies: 'For new companies', companyRegistrationNext: 'Company registration will be available in the next step.' })
Object.assign(de, { companyEntryHint: 'Wählen Sie, wie Sie fortfahren möchten.', vehicleCheck: 'FAHRZEUGCHECK', driversEmployees: 'Für Fahrer / Mitarbeiter', companyLogin: 'UNTERNEHMENS-ANMELDUNG', existingCompanyAccounts: 'Für bestehende Unternehmenskonten', createCompanyAccount: 'UNTERNEHMENSKONTO ERSTELLEN', newCompanies: 'Für neue Unternehmen', companyRegistrationNext: 'Die Unternehmensregistrierung wird im nächsten Schritt verfügbar sein.' })
Object.assign(ru, { companyEntryHint: 'Выберите, как хотите продолжить.', vehicleCheck: 'ПРОВЕРКА АВТОМОБИЛЯ', driversEmployees: 'Для водителей / сотрудников', companyLogin: 'ВХОД КОМПАНИИ', existingCompanyAccounts: 'Для существующих аккаунтов компаний', createCompanyAccount: 'СОЗДАТЬ АККАУНТ КОМПАНИИ', newCompanies: 'Для новых компаний', companyRegistrationNext: 'Регистрация компании будет доступна на следующем этапе.' })
Object.assign(lv, { companyEntryHint: 'Izvēlieties, kā vēlaties turpināt.', vehicleCheck: 'TRANSPORTLĪDZEKĻA PĀRBAUDE', driversEmployees: 'Vadītājiem / darbiniekiem', companyLogin: 'UZŅĒMUMA PIESLĒGŠANĀS', existingCompanyAccounts: 'Esošiem uzņēmumu kontiem', createCompanyAccount: 'IZVEIDOT UZŅĒMUMA KONTU', newCompanies: 'Jauniem uzņēmumiem', companyRegistrationNext: 'Uzņēmuma reģistrācija būs pieejama nākamajā solī.' })

Object.assign(en, { companyCheckHint: 'Enter the vehicle number and your name to continue.', companyVehicleNotFoundHint: 'This vehicle is not registered in FleetCheck. Please contact your company administrator.', noKnownIssues: 'No known issues', employee: 'Employee', continueCheck: 'CONTINUE CHECK' })
Object.assign(de, { companyCheckHint: 'Geben Sie die Fahrzeugnummer und Ihren Namen ein, um fortzufahren.', companyVehicleNotFoundHint: 'Dieses Fahrzeug ist nicht in FleetCheck registriert. Bitte wenden Sie sich an Ihren Unternehmensadministrator.', noKnownIssues: 'Keine bekannten Probleme', employee: 'Mitarbeiter', continueCheck: 'CHECK FORTSETZEN' })
Object.assign(ru, { companyCheckHint: 'Введите номер автомобиля и ваше имя, чтобы продолжить.', companyVehicleNotFoundHint: 'Этот автомобиль не зарегистрирован в FleetCheck. Обратитесь к администратору вашей компании.', noKnownIssues: 'Нет известных проблем', employee: 'Сотрудник', continueCheck: 'ПРОДОЛЖИТЬ ПРОВЕРКУ' })
Object.assign(lv, { companyCheckHint: 'Ievadiet transportlīdzekļa numuru un savu vārdu, lai turpinātu.', companyVehicleNotFoundHint: 'Šis transportlīdzeklis nav reģistrēts FleetCheck. Lūdzu, sazinieties ar uzņēmuma administratoru.', noKnownIssues: 'Nav zināmu problēmu', employee: 'Darbinieks', continueCheck: 'TURPINĀT PĀRBAUDI' })

Object.assign(en, { accident: 'Accident', save: 'SAVE', companyName: 'Company Name', adminName: 'Admin Name', confirmPassword: 'Confirm Password', phone: 'Phone', passwordsDoNotMatch: 'Passwords do not match.', adminDashboard: 'ADMIN DASHBOARD', editVehicle: 'EDIT VEHICLE', seenThese: 'I HAVE SEEN THESE', vehicleConditionQuestion: 'Is the vehicle condition OK?', checkComplete: 'CHECK COMPLETE', finish: 'FINISH', returnToCompanyHome: 'RETURN TO COMPANY HOME', notifications: 'Notifications', markAllRead: 'Mark all as read', noNotifications: 'No notifications' })
Object.assign(de, { accident: 'Unfall', save: 'SPEICHERN', companyName: 'Unternehmensname', adminName: 'Administratorname', confirmPassword: 'Passwort bestätigen', phone: 'Telefon', passwordsDoNotMatch: 'Die Passwörter stimmen nicht überein.', adminDashboard: 'ADMIN-DASHBOARD', editVehicle: 'FAHRZEUG BEARBEITEN', seenThese: 'ICH HABE SIE GESEHEN', vehicleConditionQuestion: 'Ist der Fahrzeugzustand in Ordnung?', checkComplete: 'CHECK ABGESCHLOSSEN', finish: 'BEENDEN', returnToCompanyHome: 'ZURÜCK ZUR UNTERNEHMENSSTARTSEITE', notifications: 'Benachrichtigungen', markAllRead: 'Alle als gelesen markieren', noNotifications: 'Keine Benachrichtigungen' })
Object.assign(ru, { accident: 'Авария', save: 'СОХРАНИТЬ', companyName: 'Название компании', adminName: 'Имя администратора', confirmPassword: 'Подтвердите пароль', phone: 'Телефон', passwordsDoNotMatch: 'Пароли не совпадают.', adminDashboard: 'ПАНЕЛЬ АДМИНИСТРАТОРА', editVehicle: 'РЕДАКТИРОВАТЬ АВТОМОБИЛЬ', seenThese: 'Я ОЗНАКОМИЛСЯ', vehicleConditionQuestion: 'Автомобиль в порядке?', checkComplete: 'ПРОВЕРКА ЗАВЕРШЕНА', finish: 'ЗАВЕРШИТЬ', returnToCompanyHome: 'ВЕРНУТЬСЯ НА ГЛАВНУЮ КОМПАНИИ', notifications: 'Уведомления', markAllRead: 'Отметить все прочитанными', noNotifications: 'Нет уведомлений' })
Object.assign(lv, { accident: 'Negadījums', save: 'SAGLABĀT', companyName: 'Uzņēmuma nosaukums', adminName: 'Administratora vārds', confirmPassword: 'Apstipriniet paroli', phone: 'Tālrunis', passwordsDoNotMatch: 'Paroles nesakrīt.', adminDashboard: 'ADMINISTRATORA PANELIS', editVehicle: 'REDIĢĒT TRANSPORTLĪDZEKLI', seenThese: 'ES TOS ESMU REDZĒJIS', vehicleConditionQuestion: 'Vai transportlīdzekļa stāvoklis ir kārtībā?', checkComplete: 'PĀRBAUDE PABEIGTA', finish: 'PABEIGT', returnToCompanyHome: 'ATGRIEZTIES UZŅĒMUMA SĀKUMLAPĀ', notifications: 'Paziņojumi', markAllRead: 'Atzīmēt visus kā lasītus', noNotifications: 'Nav paziņojumu' })

Object.assign(en, { signOut: 'SIGN OUT', finishCheck: 'FINISH CHECK' })
Object.assign(de, { signOut: 'Abmelden', finishCheck: 'Check beenden' })
Object.assign(ru, { signOut: 'ВЫЙТИ', finishCheck: 'ЗАВЕРШИТЬ ПРОВЕРКУ' })
Object.assign(lv, { signOut: 'IZRAKSTĪTIES', finishCheck: 'PABEIGT PĀRBAUDI' })

Object.assign(en, { noAccount: "Don't have an account?", backToFleetCheck: 'Back to FleetCheck' })
Object.assign(de, { noAccount: 'Noch kein Konto?', backToFleetCheck: 'Zurück zu FleetCheck' })
Object.assign(ru, { noAccount: 'Нет аккаунта?', backToFleetCheck: 'Назад в FleetCheck' })
Object.assign(lv, { noAccount: 'Vēl nav konta?', backToFleetCheck: 'Atpakaļ uz FleetCheck' })

Object.assign(en, { noVehiclesAdded: 'No vehicles added yet.', addFirstVehicleWhenReady: "You can add your first vehicle when you're ready.", backToCompanyHome: 'Back to Company Home', goToCompanyHome: 'GO TO COMPANY HOME' })
Object.assign(de, { noVehiclesAdded: 'Noch keine Fahrzeuge hinzugefügt.', addFirstVehicleWhenReady: 'Sie können Ihr erstes Fahrzeug hinzufügen, wenn Sie bereit sind.', backToCompanyHome: 'Zurück zur Unternehmensstartseite', goToCompanyHome: 'ZUR UNTERNEHMENSSTARTSEITE' })
Object.assign(ru, { noVehiclesAdded: 'Автомобили еще не добавлены.', addFirstVehicleWhenReady: 'Добавьте первый автомобиль, когда будете готовы.', backToCompanyHome: 'Назад на главную компании', goToCompanyHome: 'НА ГЛАВНУЮ КОМПАНИИ' })
Object.assign(lv, { noVehiclesAdded: 'Vēl nav pievienotu transportlīdzekļu.', addFirstVehicleWhenReady: 'Pievienojiet pirmo transportlīdzekli, kad esat gatavs.', backToCompanyHome: 'Atpakaļ uz uzņēmuma sākumlapu', goToCompanyHome: 'UZ UZŅĒMUMA SĀKUMLAPU' })

Object.assign(en, { serverConnectionFailed: 'Could not connect to the server. Please try again.' })
Object.assign(de, { serverConnectionFailed: 'Verbindung zum Server fehlgeschlagen. Bitte versuchen Sie es erneut.' })
Object.assign(ru, { serverConnectionFailed: 'Не удалось подключиться к серверу. Пожалуйста, попробуйте еще раз.' })
Object.assign(lv, { serverConnectionFailed: 'Neizdevās savienoties ar serveri. Lūdzu, mēģiniet vēlreiz.' })

Object.assign(en, { enterVehicleBrand: 'Enter vehicle brand' })
Object.assign(de, { enterVehicleBrand: 'Fahrzeugmarke eingeben' })
Object.assign(ru, { enterVehicleBrand: 'Введите марку автомобиля' })
Object.assign(lv, { enterVehicleBrand: 'Ievadiet transportlīdzekļa marku' })

Object.assign(en, { checkVehicle: 'CHECK VEHICLE', reportNewProblem: 'REPORT NEW PROBLEM', priority: 'Priority', attentionNeeded: 'Attention needed', urgent: 'Urgent', tiresWheels: 'Tires / wheels', engine: 'Engine', brakes: 'Brakes', lighting: 'Lights', bodyDamage: 'Body damage', interior: 'Interior', fluidOil: 'Fluid / oil', warningLight: 'Warning light', other: 'Other', shortDescription: 'Short description', addPhoto: 'Add photo', addVideo: 'Add video', submitReport: 'Send report', sendReport: 'SEND REPORT' })
Object.assign(de, { checkVehicle: 'FAHRZEUG PRÜFEN', reportNewProblem: 'NEUES PROBLEM MELDEN', priority: 'Priorität', attentionNeeded: 'Aufmerksamkeit erforderlich', urgent: 'Dringend', tiresWheels: 'Reifen / Räder', engine: 'Motor', brakes: 'Bremsen', lighting: 'Beleuchtung', bodyDamage: 'Karosserieschaden', interior: 'Innenraum', fluidOil: 'Flüssigkeit / Öl', warningLight: 'Warnleuchte', other: 'Sonstiges', shortDescription: 'Kurze Beschreibung', addPhoto: 'Foto hinzufügen', addVideo: 'Video hinzufügen', submitReport: 'Meldung senden', sendReport: 'MELDUNG SENDEN' })
Object.assign(ru, { checkVehicle: 'ПРОВЕРИТЬ АВТОМОБИЛЬ', reportNewProblem: 'СООБЩИТЬ О НОВОЙ ПРОБЛЕМЕ', priority: 'Приоритет', attentionNeeded: 'Требует внимания', urgent: 'Срочно', tiresWheels: 'Шины / колеса', engine: 'Двигатель', brakes: 'Тормоза', lighting: 'Освещение', bodyDamage: 'Повреждение кузова', interior: 'Салон', fluidOil: 'Жидкости / масло', warningLight: 'Сигнальная лампа', other: 'Другое', shortDescription: 'Краткое описание', addPhoto: 'Добавить фото', addVideo: 'Добавить видео', submitReport: 'Отправить отчет', sendReport: 'ОТПРАВИТЬ ОТЧЕТ' })
Object.assign(lv, { checkVehicle: 'PĀRBAUDĪT TRANSPORTLĪDZEKLI', reportNewProblem: 'ZIŅOT PAR JAUNU PROBLĒMU', priority: 'Prioritāte', attentionNeeded: 'Nepieciešama uzmanība', urgent: 'Steidzami', tiresWheels: 'Riepas / riteņi', engine: 'Dzinējs', brakes: 'Bremzes', lighting: 'Apgaismojums', bodyDamage: 'Virsbūves bojājumi', interior: 'Salons', fluidOil: 'Šķidrumi / eļļa', warningLight: 'Brīdinājuma lampiņa', other: 'Cits', shortDescription: 'Īss apraksts', addPhoto: 'Pievienot foto', addVideo: 'Pievienot video', submitReport: 'Sūtīt ziņojumu', sendReport: 'SŪTĪT ZIŅOJUMU' })

Object.assign(en, { allVehicles: 'All vehicles', noVehiclesInCategory: 'No vehicles in this category.', noUrgentVehicles: 'No urgent vehicles.', noVehiclesNeedingAttention: 'No vehicles needing attention.' })
Object.assign(de, { allVehicles: 'Alle Fahrzeuge', noVehiclesInCategory: 'Keine Fahrzeuge in dieser Kategorie.', noUrgentVehicles: 'Keine dringenden Fahrzeuge.', noVehiclesNeedingAttention: 'Keine Fahrzeuge benötigen Aufmerksamkeit.' })
Object.assign(ru, { allVehicles: 'Все автомобили', noVehiclesInCategory: 'В этой категории нет автомобилей.', noUrgentVehicles: 'Нет срочных автомобилей.', noVehiclesNeedingAttention: 'Нет автомобилей, требующих внимания.' })
Object.assign(lv, { allVehicles: 'Visi transportlīdzekļi', noVehiclesInCategory: 'Šajā kategorijā nav transportlīdzekļu.', noUrgentVehicles: 'Nav steidzamu transportlīdzekļu.', noVehiclesNeedingAttention: 'Nav transportlīdzekļu, kuriem nepieciešama uzmanība.' })

Object.assign(en, { noBrandsFound: 'No brands found.' })
Object.assign(de, { noBrandsFound: 'Keine Marken gefunden.' })
Object.assign(ru, { noBrandsFound: 'Марки не найдены.' })
Object.assign(lv, { noBrandsFound: 'Nav atrastu marku.' })

Object.assign(en, { privateSignIn: 'Sign in to My Vehicles', createPrivateAccount: 'Create private account', createAccount: 'CREATE ACCOUNT', signIn: 'SIGN IN', alreadyHaveAccount: 'Already have an account?', privateAccountRequired: 'Please sign in with a private account.', loading: 'Loading...' })
Object.assign(de, { privateSignIn: 'Bei Meine Fahrzeuge anmelden', createPrivateAccount: 'Privates Konto erstellen', createAccount: 'KONTO ERSTELLEN', signIn: 'ANMELDEN', alreadyHaveAccount: 'Bereits ein Konto?', privateAccountRequired: 'Bitte melden Sie sich mit einem privaten Konto an.', loading: 'Wird geladen...' })
Object.assign(ru, { privateSignIn: 'Войти в мои автомобили', createPrivateAccount: 'Создать личный аккаунт', createAccount: 'СОЗДАТЬ АККАУНТ', signIn: 'ВОЙТИ', alreadyHaveAccount: 'Уже есть аккаунт?', privateAccountRequired: 'Войдите с личным аккаунтом.', loading: 'Загрузка...' })
Object.assign(lv, { privateSignIn: 'Pieslēgties maniem transportlīdzekļiem', createPrivateAccount: 'Izveidot privāto kontu', createAccount: 'IZVEIDOT KONTU', signIn: 'PIESLĒGTIES', alreadyHaveAccount: 'Jau ir konts?', privateAccountRequired: 'Lūdzu, pieslēdzieties ar privāto kontu.', loading: 'Notiek ielāde...' })

Object.assign(en, { privateNameRequired: 'Please enter your name.', privateEmailInvalid: 'Please enter a valid email address.', privatePasswordLength: 'Your password must contain at least 8 characters.', privateRegistrationFailed: 'We could not create your account. Please try again.', privateLoginFailed: 'Email or password is incorrect.', privateAuthenticationFailed: 'We could not sign you in. Please try again.', vehicleCount: 'Vehicles' })
Object.assign(de, { privateNameRequired: 'Bitte geben Sie Ihren Namen ein.', privateEmailInvalid: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.', privatePasswordLength: 'Ihr Passwort muss mindestens 8 Zeichen enthalten.', privateRegistrationFailed: 'Ihr Konto konnte nicht erstellt werden. Bitte versuchen Sie es erneut.', privateLoginFailed: 'E-Mail oder Passwort ist nicht korrekt.', privateAuthenticationFailed: 'Anmeldung nicht möglich. Bitte versuchen Sie es erneut.', vehicleCount: 'Fahrzeuge' })
Object.assign(ru, { privateNameRequired: 'Введите ваше имя.', privateEmailInvalid: 'Введите действительный адрес электронной почты.', privatePasswordLength: 'Пароль должен содержать не менее 8 символов.', privateRegistrationFailed: 'Не удалось создать аккаунт. Попробуйте еще раз.', privateLoginFailed: 'Неверный email или пароль.', privateAuthenticationFailed: 'Не удалось выполнить вход. Попробуйте еще раз.', vehicleCount: 'Автомобили' })
Object.assign(lv, { privateNameRequired: 'Lūdzu, ievadiet savu vārdu.', privateEmailInvalid: 'Lūdzu, ievadiet derīgu e-pasta adresi.', privatePasswordLength: 'Parolē jābūt vismaz 8 rakstzīmēm.', privateRegistrationFailed: 'Neizdevās izveidot kontu. Lūdzu, mēģiniet vēlreiz.', privateLoginFailed: 'E-pasta adrese vai parole nav pareiza.', privateAuthenticationFailed: 'Neizdevās pieslēgties. Lūdzu, mēģiniet vēlreiz.', vehicleCount: 'Transportlīdzekļi' })

Object.assign(en,{calendar:'Calendar',reminders:'Reminders',tuv:'Technical inspection',insurance:'Insurance',service:'Service',oil_change:'Oil change',tire_change:'Tire change',upcoming:'Upcoming',overdue:'Overdue',completed:'Completed',note:'Note',addReminder:'Add reminder',markCompleted:'Mark completed',delete:'Delete'})
Object.assign(de,{calendar:'Kalender',reminders:'Erinnerungen',tuv:'Hauptuntersuchung',insurance:'Versicherung',service:'Service',oil_change:'Ölwechsel',tire_change:'Reifenwechsel',upcoming:'Anstehend',overdue:'Überfällig',completed:'Erledigt',note:'Notiz',addReminder:'Erinnerung hinzufügen',markCompleted:'Als erledigt markieren',delete:'Löschen'})
Object.assign(ru,{calendar:'Календарь',reminders:'Напоминания',tuv:'Техосмотр',insurance:'Страховка',service:'Сервис',oil_change:'Замена масла',tire_change:'Замена шин',upcoming:'Предстоит',overdue:'Просрочено',completed:'Завершено',note:'Примечание',addReminder:'Добавить напоминание',markCompleted:'Отметить как завершенное',delete:'Удалить'})
Object.assign(lv,{calendar:'Kalendārs',reminders:'Atgādinājumi',tuv:'Tehniskā apskate',insurance:'Apdrošināšana',service:'Serviss',oil_change:'Eļļas maiņa',tire_change:'Riepu maiņa',upcoming:'Gaidāms',overdue:'Nokavēts',completed:'Pabeigts',note:'Piezīme',addReminder:'Pievienot atgādinājumu',markCompleted:'Atzīmēt kā pabeigtu',delete:'Dzēst'})

Object.assign(en,{upcomingReminders:'Upcoming reminders',overdueReminders:'Overdue reminders'})
Object.assign(de,{upcomingReminders:'Anstehende Erinnerungen',overdueReminders:'Überfällige Erinnerungen'})
Object.assign(ru,{upcomingReminders:'Предстоящие напоминания',overdueReminders:'Просроченные напоминания'})
Object.assign(lv,{upcomingReminders:'Gaidāmie atgādinājumi',overdueReminders:'Nokavētie atgādinājumi'})

export const translations = { de, en, ru, lv }
