import { useEffect, useState } from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import Header from '../../components/Header/Header'
import { useLanguage } from '../../context/LanguageContext'
import { getPrivateVehicles } from '../../services/privateApiService'
import { getReminders } from '../../services/reminderService'
import { isPrivateLoggedIn } from '../../services/sessionService'
import styles from './PrivateHome.module.css'
function PrivateHome(){const{t}=useLanguage();const navigate=useNavigate();const[vehicles,setVehicles]=useState([]);const[reminders,setReminders]=useState([]);useEffect(()=>{Promise.all([getPrivateVehicles(),getReminders('private')]).then(([v,r])=>{setVehicles(v);setReminders(r)})},[]);if(!isPrivateLoggedIn())return <Navigate to="/private/auth" replace/>;const today=new Date().toISOString().slice(0,10);const upcoming=reminders.filter(r=>r.status!=='COMPLETED'&&r.due_date>=today).length;const overdue=reminders.filter(r=>r.status!=='COMPLETED'&&r.due_date<today).length;return <div className={styles.page}><Header role="privateRole"/><main className={styles.main}><section className={styles.intro}><h1>{t('myVehicles')}</h1><p>{t('privateHomeHint')}</p><Link to="/private/calendar">{t('calendar')}</Link></section><section className={styles.reminderStats}><Link to="/private/calendar">{t('upcomingReminders')}: <strong>{upcoming}</strong></Link><Link to="/private/calendar">{t('overdueReminders')}: <strong>{overdue}</strong></Link></section><section className={styles.vehicleList}>{vehicles.map(v=><article className={styles.vehicleCard} key={v.id}><h2>{v.brand} {v.model}</h2><p className={styles.plate}>{v.plateNumber}</p><div className={styles.actions}><button className={styles.okButton} onClick={()=>navigate(`/home/private/vehicle/${v.id}/ok`)}>{t('vehicleOk')}</button><button className={styles.secondaryButton} onClick={()=>navigate(`/home/private/vehicle/${v.id}/report`)}>{t('reportProblem')}</button><button className={styles.secondaryButton} onClick={()=>navigate(`/home/private/vehicle/${v.id}/history`)}>{t('vehicleHistory')}</button></div></article>)}</section></main></div>}
export default PrivateHome
