import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import Header from '../../components/Header/Header'
import VehicleNotFound from '../../components/VehicleNotFound/VehicleNotFound'
import { useLanguage } from '../../context/LanguageContext'
import { createCompanyReport, getCompanyVehicle, getVehicleIssues } from '../../services/companyApiService'
import { clearDriverSession, getDriverSession } from '../../services/sessionService'
import styles from './CompanyVehicleCheck.module.css'

function CompanyVehicleCheck() {
  const { vehicleId } = useParams(); const { t } = useLanguage(); const navigate = useNavigate(); const session = getDriverSession(); const [vehicle, setVehicle] = useState(null); const [issues, setIssues] = useState([]); const [seen, setSeen] = useState(false); const [stage, setStage] = useState('issues'); const [media, setMedia] = useState(null); const [preview, setPreview] = useState(''); const [error, setError] = useState(''); const photoRef = useRef(null); const videoRef = useRef(null)
  useEffect(() => { Promise.all([getCompanyVehicle(vehicleId), getVehicleIssues(vehicleId)]).then(([loadedVehicle, loadedIssues]) => { setVehicle(loadedVehicle); setIssues(loadedIssues); setSeen(!loadedIssues.length) }).catch(() => setVehicle(false)) }, [vehicleId])
  if (vehicle === false) return <VehicleNotFound />
  if (!vehicle) return null
  const select = (event) => { const file = event.target.files?.[0]; if (!file) return; setMedia(file); setPreview(URL.createObjectURL(file)) }
  const saveOk = async () => { setError(''); try { await createCompanyReport({ vehicleId: vehicle.id, employeeName: session?.employeeName || '', type: 'VEHICLE_OK' }, media); setStage('complete') } catch (requestError) { setError(requestError.message) } }
  const finishCheck = () => { clearDriverSession(); navigate('/company/check') }
  return <div className={styles.page}><Header /><main className={styles.main}><Link className={styles.back} to="/company/check">{t('back')}</Link><section className={styles.vehicleInfo}><h1>{vehicle.brand} {vehicle.model}</h1><p>{vehicle.plateNumber}</p><small>{t('employee')}: {session?.employeeName || ''}</small></section>{stage === 'issues' && <section className={styles.card}><h2>{t('knownIssues')}</h2>{issues.length ? <div className={styles.list}>{issues.map((issue) => <article className={styles.issue} key={issue.id}><strong>{t(issue.issueType)}</strong><p>{issue.description}</p></article>)}</div> : <p className={styles.empty}>{t('noKnownIssues')}</p>}{issues.length > 0 && <button className={styles.continue} type="button" onClick={() => setSeen(true)}>{t('seenThese')}</button>}<button className={styles.continue} type="button" disabled={!seen} onClick={() => setStage('inspect')}>{t('continueCheck')}</button></section>}{stage === 'inspect' && <section className={styles.card}><h2>{t('vehicleConditionQuestion')}</h2><div className={styles.media}><label>{t('addPhoto')}<input ref={photoRef} type="file" accept="image/jpeg,image/png,image/webp,image/heic" capture="environment" onChange={select} /></label><label>{t('addVideo')}<input ref={videoRef} type="file" accept="video/mp4,video/quicktime" capture="environment" onChange={select} /></label></div>{preview && media?.type.startsWith('image/') && <img className={styles.preview} src={preview} alt={t('photo')} />}{preview && media?.type.startsWith('video/') && <video className={styles.preview} controls src={preview} />} {error && <p className={styles.empty}>{error}</p>}<button className={styles.continue} type="button" onClick={saveOk}>{t('everythingOk')}</button><button className={styles.report} type="button" onClick={() => navigate(`/company/check/${vehicle.id}/report`)}>{t('reportProblem')}</button></section>}{stage === 'complete' && <section className={styles.card}><h2>{t('checkComplete')}</h2><p>{t('vehicle')}: {vehicle.plateNumber}<br />{t('employee')}: {session?.employeeName || ''}</p><button className={styles.continue} type="button" onClick={finishCheck}>{t('finishCheck')}</button><button className={styles.report} type="button" onClick={() => navigate('/company/home')}>{t('returnToCompanyHome')}</button></section>}</main></div>
}
export default CompanyVehicleCheck
