import { useEffect, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import Header from '../../components/Header/Header'
import { useLanguage } from '../../context/LanguageContext'
import { getCompanyDashboard, getCompanyVehicles, getVehicleIssues, updateCompanyReportStatus } from '../../services/companyApiService'
import { getReminders } from '../../services/reminderService'
import { isCompanyAdmin } from '../../services/sessionService'
import styles from './AdminDashboard.module.css'

const category = (reports) => reports.some((report) => report.priority === 'urgent') ? 'URGENT' : reports.length ? 'ATTENTION' : 'OK'
function AdminDashboard() {
  const { t } = useLanguage(); const [dashboard,setDashboard]=useState(null); const [vehicles,setVehicles]=useState([]); const [issues,setIssues]=useState({}); const [reminders,setReminders]=useState([]); const [filter,setFilter]=useState('ALL')
  const load=()=>Promise.all([getCompanyDashboard(),getCompanyVehicles(),getReminders('company')]).then(async([data,items,dates])=>{setDashboard(data);setVehicles(items);setReminders(dates);setIssues(Object.fromEntries(await Promise.all(items.map(async item=>[item.id,await getVehicleIssues(item.id).catch(()=>[])]))))})
  useEffect(()=>{if(isCompanyAdmin())load().catch(()=>setDashboard({stats:{totalVehicles:0,vehiclesOk:0,needAttention:0,urgent:0},recentReports:[]}))},[])
  if(!isCompanyAdmin())return <Navigate to="/company/driver" replace />
  const stats=dashboard?.stats||{totalVehicles:0,vehiclesOk:0,needAttention:0,urgent:0}; const today=new Date().toISOString().slice(0,10); const upcoming=reminders.filter(r=>r.status!=='COMPLETED'&&r.due_date>=today).length; const overdue=reminders.filter(r=>r.status!=='COMPLETED'&&r.due_date<today).length; const cards=[{label:t('totalVehicles'),value:stats.totalVehicles,key:'ALL'},{label:t('vehiclesOk'),value:stats.vehiclesOk,key:'OK'},{label:t('needAttention'),value:stats.needAttention,key:'ATTENTION'},{label:t('urgent'),value:stats.urgent,key:'URGENT'}]; const visible=vehicles.filter(v=>filter==='ALL'||category(issues[v.id]||[])===filter); const update=async(id,status)=>{await updateCompanyReportStatus(id,status);load()}
  return <div className={styles.page}><Header admin/><main className={styles.main}><div className={styles.title}><p>FLEET MANAGEMENT</p><h1>{t('dashboard')}</h1><nav className={styles.quickActions}><Link to="/company/vehicles">{t('vehicles')}</Link><Link to="/company/setup">{t('addVehicle')}</Link><Link to="/company/reports">{t('reports')}</Link><Link to="/company/employees">{t('employees')}</Link><Link to="/company/calendar">{t('calendar')}</Link></nav></div><section className={styles.stats}>{cards.map(card=><button className={styles.stat} key={card.key} onClick={()=>setFilter(card.key)}><p>{card.label}</p><strong>{card.value}</strong></button>)}<Link className={styles.stat} to="/company/calendar"><p>{t('upcomingReminders')}</p><strong>{upcoming}</strong></Link><Link className={styles.stat} to="/company/calendar"><p>{t('overdueReminders')}</p><strong>{overdue}</strong></Link></section><section className={styles.panel}><h2>{t('fleetVehicles')} ({visible.length})</h2><div className={styles.vehicleGrid}>{visible.map(v=><Link className={styles.vehicleCard} key={v.id} to={`/admin/vehicle/${v.id}`}><b>{v.plateNumber}</b><span>{v.brand} {v.model}</span><span className={styles.badge}>{category(issues[v.id]||[])}</span></Link>)}</div></section><section className={styles.panel}><h2>{t('recentReports')}</h2>{dashboard?.recentReports?.map(r=><article key={r.id}><Link to={`/admin/vehicle/${r.vehicle_id}`}>{r.type==='ISSUE'?t(r.issue_type?.toLowerCase()):t('vehicleOk')}</Link>{r.type==='ISSUE'&&<select value={r.status} onChange={e=>update(r.id,e.target.value)}><option value="OPEN">{t('open')}</option><option value="IN_REPAIR">{t('inRepair')}</option><option value="RESOLVED">{t('resolved')}</option></select>}</article>)}</section></main></div>
}
export default AdminDashboard
