import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import Header from '../../components/Header/Header'
import VehicleNotFound from '../../components/VehicleNotFound/VehicleNotFound'
import { useLanguage } from '../../context/LanguageContext'
import { createCompanyReport, getCompanyVehicle } from '../../services/companyApiService'
import { clearDriverSession, getDriverSession } from '../../services/sessionService'
import styles from './CompanyReportIssue.module.css'

const categories = ['tiresWheels', 'engine', 'brakes', 'lights', 'bodyDamage', 'interior', 'fluidOil', 'warningLight', 'other']
function CompanyReportIssue() {
  const { vehicleId } = useParams(); const { t } = useLanguage(); const navigate = useNavigate(); const session = getDriverSession(); const [vehicle, setVehicle] = useState(null); const [issueType, setIssueType] = useState(''); const [priority, setPriority] = useState('attention'); const [description, setDescription] = useState(''); const [media, setMedia] = useState(null); const [preview, setPreview] = useState(''); const [done, setDone] = useState(false); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const photoRef = useRef(null); const videoRef = useRef(null)
  useEffect(() => { getCompanyVehicle(vehicleId).then(setVehicle).catch(() => setVehicle(false)) }, [vehicleId])
  const select = (event) => { const file = event.target.files?.[0]; if (!file) return; setMedia(file); setPreview(URL.createObjectURL(file)) }
  const remove = (ref) => { setMedia(null); setPreview(''); if (ref.current) ref.current.value = '' }
  const submit = async (event) => { event.preventDefault(); if (!issueType || !vehicle) return; setSubmitting(true); setError(''); try { await createCompanyReport({ vehicleId: vehicle.id, employeeName: session?.employeeName || '', type: 'ISSUE', issueType, priority, description: description.trim() }, media); setDone(true) } catch (requestError) { setError(requestError.message) } finally { setSubmitting(false) } }
  const finishCheck = () => { clearDriverSession(); navigate('/company/check') }
  if (vehicle === false) return <VehicleNotFound />
  return <div className={styles.page}><Header /><main className={styles.main}>{done ? <section className={styles.card}><h1>{t('reportSent')}</h1><p>{t('vehicle')}: {vehicle?.plateNumber}<br />{t('employee')}: {session?.employeeName || ''}</p><button type="button" onClick={finishCheck}>{t('finishCheck')}</button><button type="button" onClick={() => navigate('/company/home')}>{t('returnToCompanyHome')}</button></section> : <form className={styles.card} onSubmit={submit}><h1>{t('reportProblem')}</h1><div className={styles.categories}>{categories.map((item) => <button className={issueType === item ? styles.selected : ''} type="button" key={item} onClick={() => setIssueType(item)}>{t(item)}</button>)}</div><fieldset className={styles.priority}><legend>{t('priority')}</legend><label><input type="radio" name="priority" value="attention" checked={priority === 'attention'} onChange={(event) => setPriority(event.target.value)} />{t('attentionNeeded')}</label><label><input type="radio" name="priority" value="urgent" checked={priority === 'urgent'} onChange={(event) => setPriority(event.target.value)} />{t('urgent')}</label></fieldset><label>{t('shortDescription')}<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className={styles.media}><label>{t('addPhoto')}<input ref={photoRef} type="file" accept="image/jpeg,image/png,image/webp,image/heic" capture="environment" onChange={select} /></label><label>{t('addVideo')}<input ref={videoRef} type="file" accept="video/mp4,video/quicktime" capture="environment" onChange={select} /></label></div>{preview && media?.type.startsWith('image/') && <section className={styles.preview}><img src={preview} alt={t('photo')} /><button type="button" onClick={() => remove(photoRef)}>{t('remove')}</button></section>}{preview && media?.type.startsWith('video/') && <section className={styles.preview}><video controls src={preview} /><button type="button" onClick={() => remove(videoRef)}>{t('remove')}</button></section>}{error && <p>{error}</p>}<button disabled={!issueType || submitting || !vehicle}>{t('sendReport')}</button></form>}</main></div>
}
export default CompanyReportIssue
